# Generated by Django 3.2.21 on 2023-10-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('question', models.TextField()),
                ('answer', models.TextField(default='Thanks for contacting us.We will get back to you soon')),
                ('subscribe', models.BooleanField()),
            ],
            options={
                'ordering': ['-question'],
            },
        ),
    ]
