# Generated by Django 3.2.21 on 2023-10-15 22:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20231015_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
