# Generated by Django 3.2.21 on 2023-10-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_package_package_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='reviews',
            field=models.TextField(blank=True, null=True),
        ),
    ]
