# Generated by Django 3.2.21 on 2023-10-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='reviews',
        ),
    ]
