# Generated by Django 3.2.21 on 2023-10-28 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_package_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='rating',
        ),
    ]
